#:import hex kivy.utils.get_color_from_hex
<ScreenHome>:
    canvas:
        Color:
            rgba: hex('#aefbcd')
        Rectangle:
            pos: self.x + 5, self.y + 120
            size: self.width - 10, self.height - 240
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 60
            spacing: 5
            padding: 5
            Button:
                text: "CHẠY"
                size_hint_x: None
                width: 120
                on_press: app.m_run(True)
                on_release: app.m_run(False)
            Button:
                text: "DỪNG"
                size_hint_x: None
                width: 120
                on_press: app.m_stop(True)
                on_release: app.m_stop(False)
            Widget:
            Label:
                text: 'CẤU HÌNH'
                size_hint_x: None
                font_size: 20
                width: 100
                halign: 'left'
                valign: 'center'
                text_size: self.size
            TextInput:
                id: profile_name
                size_hint_x: None
                font_size: 30
                width: 480
                halign: 'left'
                input_filter: root._file_name_filter
                multiline: False
                text_size: self.size
            Button:
                text: "MỞ"
                size_hint_x: None
                width: 120
                on_press: root._profile_load_select()
            Button:
                text: "LƯU"
                size_hint_x: None
                width: 120
                on_press: root._profile_save()
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 60
            spacing: 5
            padding: 5
            Button:
                id: face_4
                size_hint_x: 0.3
                on_press: root._select_face(self)
            Button:
                id: face_2
                size_hint_x: 0.5
                on_press: root._select_face(self)
            Button:
                id: face_0
                size_hint_x: 1.0
                on_press: root._select_face(self)
        Widget:
            id: area
            canvas:
                Color:
                    rgba: 1, 0, 0, 1
                Line:
                    ellipse: (self.x + self.width * 0.5 - 50, self.y + self.height * 0.5 - 50, 100, 100)
                    width: 2
                Ellipse:
                    pos: self.x + self.width * 0.5 - 40, self.y + self.height * 0.5 - 40
                    size: 80, 80
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 60
            spacing: 5
            padding: 5
            Button:
                id: face_5
                size_hint_x: 0.3
                on_press: root._select_face(self)
            Button:
                id: face_3
                size_hint_x: 0.5
                on_press: root._select_face(self)
            Button:
                id: face_1
                size_hint_x: 1.0
                on_press: root._select_face(self)
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 60
            spacing: 5
            padding: 5
            Button:
                id: cnc_0
                size_hint_x: None
                width: 90
                on_press: root._download_cnc_select(self)
            Button:
                id: cnc_1
                size_hint_x: None
                width: 90
                on_press: root._download_cnc_select(self)
            Button:
                id: cnc_2
                size_hint_x: None
                width: 90
                on_press: root._download_cnc_select(self)
            Button:
                id: cnc_3
                size_hint_x: None
                width: 90
                on_press: root._download_cnc_select(self)
            Button:
                id: cnc_4
                size_hint_x: None
                width: 90
                on_press: root._download_cnc_select(self)
            Button:
                id: cnc_5
                size_hint_x: None
                width: 90
                on_press: root._download_cnc_select(self)
            Widget:
            Button:
                text: "LOAD"
                size_hint_x: None
                width: 120
                on_press: root.manager.current = 'load'
            Button:
                text: "IN/OUT"
                size_hint_x: None
                width: 120
                on_press: root.manager.current = 'io'
            Button:
                text: "CÀI ĐẶT"
                size_hint_x: None
                width: 120
                on_press: root.manager.current = 'setting'