<ScreenSettingAdvanced>:
    BoxLayout:
        orientation: 'vertical'
        padding: 5
        spacing: 5
        BoxLayout:
            orientation: 'horizontal'
            size_hint: None, None
            size: 120, 60
            spacing: 5
            padding: 5
            Button:
                text: "THOÁT"
                on_press: root.manager.current = 'setting'
        GridLayout:
            id: grid
            spacing: 5
            padding: 5
            size_hint_y: 1.0
        BoxLayout:
            orientation: 'horizontal'
            size_hint: None, None
            size: 240, 60
            spacing: 5
            padding: 5
            Button:
                id: hmi.cfsh.accept
                text: 'LƯU'
                on_press: app.save_accept()
            Button:
                id: hmi.cfsh.decline
                text: 'KHÔNG'
                on_press: app.save_decline()