#:import hex kivy.utils.get_color_from_hex
<ScreenHome>:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 60
            spacing: 5
            padding: 5
            Button:
                id: run
                text: "CHẠY"
                size_hint_x: None
                width: 70
                on_press: root.m_run(True)
                on_release: root.m_run(False)
            Button:
                id: stop
                text: "DỪNG"
                size_hint_x: None
                width: 70
                on_press: root.m_stop(True)
                on_release: root.m_stop(False)
            Button:
                id: face_run
                text: "CHẠY MẶT"
                size_hint_x: None
                width: 110
                on_press: root.m_face_run(True)
                on_release: root.m_face_run(False)
            Button:
                id: face_to_org
                text: "TỚI GỐC MẶT"
                size_hint_x: None
                width: 135
                on_press: root.m_face_to_org(True)
                on_release: root.m_face_to_org(False)
            Widget:
            TextInput:
                id: profile_name
                size_hint_x: None
                font_size: 30
                width: 360
                halign: 'left'
                multiline: False
                text_size: self.size
            Button:
                text: "TẢI XUỐNG"
                size_hint_x: None
                width: 120
                on_press: root._profile_download()
            Button:
                text: "MỞ"
                size_hint_x: None
                width: 60
                on_press: root._profile_load()
            Button:
                text: "LƯU"
                size_hint_x: None
                width: 60
                on_press: root._profile_save()
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 60
            spacing: 5
            padding: 5
            Button:
                id: face_4
                size_hint_x: 0.2
                on_press: root._face_select(self)
            Button:
                id: face_2
                size_hint_x: 0.3
                on_press: root._face_select(self)
            Button:
                id: face_0
                size_hint_x: 1.0
                on_press: root._face_select(self)
        BoxLayout:
            orientation: 'vertical'
            padding: 5
            spacing: 5
            StencilView:
                id: area_top
                canvas.before:
                    Color:
                        rgba: hex('#ffffff')
                    Rectangle:
                        pos: self.x, self.y
                        size: self.width, self.height
            StencilView:
                id: area_front
                canvas.before:
                    Color:
                        rgba: hex('#ffffff')
                    Rectangle:
                        pos: self.x, self.y
                        size: self.width, self.height
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 60
            spacing: 5
            padding: 5
            Button:
                id: face_5
                size_hint_x: 0.2
                on_press: root._face_select(self)
            Button:
                id: face_3
                size_hint_x: 0.3
                on_press: root._face_select(self)
            Button:
                id: face_1
                size_hint_x: 1.0
                on_press: root._face_select(self)
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 60
            spacing: 5
            padding: 5
            Button:
                id: cnc_0
                size_hint_x: None
                width: 90
                on_press: root._cnc_download(self)
            Button:
                id: cnc_1
                size_hint_x: None
                width: 90
                on_press: root._cnc_download(self)
            Button:
                id: cnc_2
                size_hint_x: None
                width: 90
                on_press: root._cnc_download(self)
            Button:
                id: cnc_3
                size_hint_x: None
                width: 90
                on_press: root._cnc_download(self)
            Button:
                id: cnc_4
                size_hint_x: None
                width: 90
                on_press: root._cnc_download(self)
            Button:
                id: cnc_5
                size_hint_x: None
                width: 90
                on_press: root._cnc_download(self)
            Widget:
            Button:
                text: "IN/OUT"
                size_hint_x: None
                width: 120
                on_press: root.manager.current = 'io'
            Button:
                text: "CÀI ĐẶT"
                size_hint_x: None
                width: 120
                on_press: root.manager.current = 'setting'