#:import hex kivy.utils.get_color_from_hex
<PopupFaceOrigin>:
    size_hint: 0.5, 0.5
    auto_dismiss: False
    BoxLayout:
        orientation: 'vertical'
        Widget:
            size_hint_y: None
            height: 10
        BoxLayout:
            id: main
            orientation: 'horizontal'
            spacing: 5
            BoxLayout:
                GridLayout:
                    spacing: 5
                    padding: 5
                    cols: 3
                    rows: 3
                    size_hint_x: None
                    width: self.height
                    Widget:
                    Button:
                        id: edge_yp
                        text: 'Y+'
                    Widget:
                    Button:
                        id: edge_xn
                        text: 'X-'
                    Button:
                        id: edge_center
                        text: 'Z'
                    Button:
                        id: edge_xp
                        text: 'X+'
                    Widget:
                    Button:
                        id: edge_yn
                        text: 'Y-'
                    Widget:
        Widget:
            size_hint_y: None
            height: 10
        BoxLayout:
            orientation: 'horizontal'
            spacing: 5
            size_hint_y: None
            height: 60
            Button:
                text: 'SET'
                size_hint_x: None
                width: 120
                on_release: root._apply()
            Widget:
            Button:
                text: 'THOÁT'
                size_hint_x: None
                width: 120
                on_release: root._cancel()