#:import hex kivy.utils.get_color_from_hex
<PopupProgress>:
    BoxLayout:
        orientation: 'vertical'
        ProgressBar:
            id: bar
            max: 100
            value: 0
        BoxLayout:
            orientation: 'horizontal'
            spacing: 5
            padding: 5
            size_hint_y: None
            height: 60
            Label:
                id: state
                font_size: 25
                bold: True
                text: 'XONG'
                halign: 'left'
                size_hint_x: None
                width: 120
                opacity: 0.0
                height: self.texture_size[1]
            Widget:
            Button:
                id: cancel
                text: 'THOÁT'
                size_hint_x: None
                width: 90
                on_release: root._cancel()