#:import hex kivy.utils.get_color_from_hex
<PopupFace>:
    size_hint: 0.9, 0.9
    auto_dismiss: False
    BoxLayout:
        orientation: 'vertical'
        Widget:
            size_hint_y: None
            height: 10
        BoxLayout:
            id: main
            orientation: 'horizontal'
            spacing: 5
            BoxLayout:
                id: face_property
                orientation: 'vertical'
                spacing: 5
                size_hint_x: None
            StencilView:
                id: area
                canvas.before:
                    Color:
                        rgba: hex('#b084bf')
                    Rectangle:
                        pos: self.x, self.y
                        size: self.width, self.height
        Widget:
            size_hint_y: None
            height: 10
        BoxLayout:
            orientation: 'horizontal'
            spacing: 5
            size_hint_y: None
            height: 60
            Button:
                text: 'XOÁ'
                size_hint_x: None
                width: 120
                on_release: root._delete()
            Button:
                text: 'ÁP DỤNG'
                size_hint_x: None
                width: 120
                on_release: root._apply()
            Widget:
            Button:
                id: face_org_set_popup
                text: "SET GỐC"
                size_hint_x: None
                width: 135
                on_press: root._face_org_set_popup()
            Button:
                id: face_to_org
                text: "TIẾN TỚI GỐC"
                size_hint_x: None
                width: 135
                on_press: root._face_to_org(True)
                on_release: root._face_to_org(False)
            Button:
                id: face_run
                text: "CHẠY MẶT"
                size_hint_x: None
                width: 110
                on_press: root._face_run(True)
                on_release: root._face_run(False)
            Widget:
            Button:
                text: 'THOÁT'
                size_hint_x: None
                width: 120
                on_release: root._cancel()