#:import hex kivy.utils.get_color_from_hex
<PopupFace>:
    BoxLayout:
        orientation: 'vertical'
        Widget:
            size_hint_y: None
            height: 10
        BoxLayout:
            orientation: 'horizontal'
            spacing: 5
            BoxLayout:
                id: face_property
                orientation: 'vertical'
                spacing: 5
                size_hint_x: None
            BoxLayout:
                id: area
                canvas.before:
                    Color:
                        rgba: hex('#b084bf')
                    Rectangle:
                        pos: self.x, self.y
                        size: self.width, self.height
        Widget:
            size_hint_y: None
            height: 10
        BoxLayout:
            orientation: 'horizontal'
            spacing: 5
            size_hint_y: None
            height: 60
            Button:
                text: 'XOÁ'
                size_hint_x: None
                width: 120
                on_release: root._delete()
            Widget:
            Button:
                text: 'ÁP DỤNG'
                size_hint_x: None
                width: 120
                on_release: root._apply()
            Widget:
            Button:
                text: 'THOÁT'
                size_hint_x: None
                width: 120
                on_release: root._cancel()