<PopupConfirm>:
    title: 'XÁC NHẬN'
    size_hint: None, None
    size: 480, 240
    auto_dismiss: False
    BoxLayout:
        orientation: 'vertical'
        Label:
            id: message
            halign: 'center'
            valign: 'middle'
            text_size: self.size
        BoxLayout:
            orientation: 'horizontal'
            spacing: 5
            size_hint_y: None
            height: 60
            Button:
                text: 'CÓ'
                on_release: root._confirm()
            Button:
                text: 'KHÔNG'
                on_release: root._cancel()