Script_Draw_limits = 11

local draw_id = {
    size_x = "@W_1#Application.M.hmi.sv.max_micro[0]",
    size_y = "@W_1#Application.M.hmi.sv.max_micro[1]",
    p_count = "@W_1#Application.M.hmi.pf.p_count",
    p_x = "@W_1#Application.M.hmi.view_axis_micro[0]",
    p_y = "@W_1#Application.M.hmi.view_axis_micro[1]",
    p_index = "@W_1#Application.M.hmi.pf_p_index"
}

local draw_spec = {
    index_edge_count = 4,
    rect_w = 520,
    rect_h = 300
}

local draw_id_px = {
	"@W_1#Application.M.hmi.pf.px[0]",
	"@W_1#Application.M.hmi.pf.px[1]",
	"@W_1#Application.M.hmi.pf.px[2]",
	"@W_1#Application.M.hmi.pf.px[3]",
	"@W_1#Application.M.hmi.pf.px[4]",
	"@W_1#Application.M.hmi.pf.px[5]",
	"@W_1#Application.M.hmi.pf.px[6]",
	"@W_1#Application.M.hmi.pf.px[7]",
	"@W_1#Application.M.hmi.pf.px[8]",
	"@W_1#Application.M.hmi.pf.px[9]",
	"@W_1#Application.M.hmi.pf.px[10]",
	"@W_1#Application.M.hmi.pf.px[11]",
	"@W_1#Application.M.hmi.pf.px[12]",
	"@W_1#Application.M.hmi.pf.px[13]",
	"@W_1#Application.M.hmi.pf.px[14]",
	"@W_1#Application.M.hmi.pf.px[15]",
	"@W_1#Application.M.hmi.pf.px[16]",
	"@W_1#Application.M.hmi.pf.px[17]",
	"@W_1#Application.M.hmi.pf.px[18]",
	"@W_1#Application.M.hmi.pf.px[19]",
	"@W_1#Application.M.hmi.pf.px[20]",
	"@W_1#Application.M.hmi.pf.px[21]",
	"@W_1#Application.M.hmi.pf.px[22]",
	"@W_1#Application.M.hmi.pf.px[23]",
	"@W_1#Application.M.hmi.pf.px[24]",
	"@W_1#Application.M.hmi.pf.px[25]",
	"@W_1#Application.M.hmi.pf.px[26]",
	"@W_1#Application.M.hmi.pf.px[27]",
	"@W_1#Application.M.hmi.pf.px[28]",
	"@W_1#Application.M.hmi.pf.px[29]",
	"@W_1#Application.M.hmi.pf.px[30]",
	"@W_1#Application.M.hmi.pf.px[31]",
	"@W_1#Application.M.hmi.pf.px[32]",
	"@W_1#Application.M.hmi.pf.px[33]",
	"@W_1#Application.M.hmi.pf.px[34]",
	"@W_1#Application.M.hmi.pf.px[35]",
	"@W_1#Application.M.hmi.pf.px[36]",
	"@W_1#Application.M.hmi.pf.px[37]",
	"@W_1#Application.M.hmi.pf.px[38]",
	"@W_1#Application.M.hmi.pf.px[39]",
	"@W_1#Application.M.hmi.pf.px[40]",
	"@W_1#Application.M.hmi.pf.px[41]",
	"@W_1#Application.M.hmi.pf.px[42]",
	"@W_1#Application.M.hmi.pf.px[43]",
	"@W_1#Application.M.hmi.pf.px[44]",
	"@W_1#Application.M.hmi.pf.px[45]",
	"@W_1#Application.M.hmi.pf.px[46]",
	"@W_1#Application.M.hmi.pf.px[47]",
	"@W_1#Application.M.hmi.pf.px[48]",
	"@W_1#Application.M.hmi.pf.px[49]",
	"@W_1#Application.M.hmi.pf.px[50]",
	"@W_1#Application.M.hmi.pf.px[51]",
	"@W_1#Application.M.hmi.pf.px[52]",
	"@W_1#Application.M.hmi.pf.px[53]",
	"@W_1#Application.M.hmi.pf.px[54]",
	"@W_1#Application.M.hmi.pf.px[55]",
	"@W_1#Application.M.hmi.pf.px[56]",
	"@W_1#Application.M.hmi.pf.px[57]",
	"@W_1#Application.M.hmi.pf.px[58]",
	"@W_1#Application.M.hmi.pf.px[59]",
	"@W_1#Application.M.hmi.pf.px[60]",
	"@W_1#Application.M.hmi.pf.px[61]",
	"@W_1#Application.M.hmi.pf.px[62]",
	"@W_1#Application.M.hmi.pf.px[63]",
	"@W_1#Application.M.hmi.pf.px[64]",
	"@W_1#Application.M.hmi.pf.px[65]",
	"@W_1#Application.M.hmi.pf.px[66]",
	"@W_1#Application.M.hmi.pf.px[67]",
	"@W_1#Application.M.hmi.pf.px[68]",
	"@W_1#Application.M.hmi.pf.px[69]",
	"@W_1#Application.M.hmi.pf.px[70]",
	"@W_1#Application.M.hmi.pf.px[71]",
	"@W_1#Application.M.hmi.pf.px[72]",
	"@W_1#Application.M.hmi.pf.px[73]",
	"@W_1#Application.M.hmi.pf.px[74]",
	"@W_1#Application.M.hmi.pf.px[75]",
	"@W_1#Application.M.hmi.pf.px[76]",
	"@W_1#Application.M.hmi.pf.px[77]",
	"@W_1#Application.M.hmi.pf.px[78]",
	"@W_1#Application.M.hmi.pf.px[79]",
	"@W_1#Application.M.hmi.pf.px[80]",
	"@W_1#Application.M.hmi.pf.px[81]",
	"@W_1#Application.M.hmi.pf.px[82]",
	"@W_1#Application.M.hmi.pf.px[83]",
	"@W_1#Application.M.hmi.pf.px[84]",
	"@W_1#Application.M.hmi.pf.px[85]",
	"@W_1#Application.M.hmi.pf.px[86]",
	"@W_1#Application.M.hmi.pf.px[87]",
	"@W_1#Application.M.hmi.pf.px[88]",
	"@W_1#Application.M.hmi.pf.px[89]",
	"@W_1#Application.M.hmi.pf.px[90]",
	"@W_1#Application.M.hmi.pf.px[91]",
	"@W_1#Application.M.hmi.pf.px[92]",
	"@W_1#Application.M.hmi.pf.px[93]",
	"@W_1#Application.M.hmi.pf.px[94]",
	"@W_1#Application.M.hmi.pf.px[95]",
	"@W_1#Application.M.hmi.pf.px[96]",
	"@W_1#Application.M.hmi.pf.px[97]",
	"@W_1#Application.M.hmi.pf.px[98]",
	"@W_1#Application.M.hmi.pf.px[99]",
	"@W_1#Application.M.hmi.pf.px[100]",
	"@W_1#Application.M.hmi.pf.px[101]",
	"@W_1#Application.M.hmi.pf.px[102]",
	"@W_1#Application.M.hmi.pf.px[103]",
	"@W_1#Application.M.hmi.pf.px[104]",
	"@W_1#Application.M.hmi.pf.px[105]",
	"@W_1#Application.M.hmi.pf.px[106]",
	"@W_1#Application.M.hmi.pf.px[107]",
	"@W_1#Application.M.hmi.pf.px[108]",
	"@W_1#Application.M.hmi.pf.px[109]",
	"@W_1#Application.M.hmi.pf.px[110]",
	"@W_1#Application.M.hmi.pf.px[111]",
	"@W_1#Application.M.hmi.pf.px[112]",
	"@W_1#Application.M.hmi.pf.px[113]",
	"@W_1#Application.M.hmi.pf.px[114]",
	"@W_1#Application.M.hmi.pf.px[115]",
	"@W_1#Application.M.hmi.pf.px[116]",
	"@W_1#Application.M.hmi.pf.px[117]",
	"@W_1#Application.M.hmi.pf.px[118]",
	"@W_1#Application.M.hmi.pf.px[119]",
	"@W_1#Application.M.hmi.pf.px[120]",
	"@W_1#Application.M.hmi.pf.px[121]",
	"@W_1#Application.M.hmi.pf.px[122]",
	"@W_1#Application.M.hmi.pf.px[123]",
	"@W_1#Application.M.hmi.pf.px[124]",
	"@W_1#Application.M.hmi.pf.px[125]",
	"@W_1#Application.M.hmi.pf.px[126]",
	"@W_1#Application.M.hmi.pf.px[127]",
	"@W_1#Application.M.hmi.pf.px[128]",
	"@W_1#Application.M.hmi.pf.px[129]",
	"@W_1#Application.M.hmi.pf.px[130]",
	"@W_1#Application.M.hmi.pf.px[131]",
	"@W_1#Application.M.hmi.pf.px[132]",
	"@W_1#Application.M.hmi.pf.px[133]",
	"@W_1#Application.M.hmi.pf.px[134]",
	"@W_1#Application.M.hmi.pf.px[135]",
	"@W_1#Application.M.hmi.pf.px[136]",
	"@W_1#Application.M.hmi.pf.px[137]",
	"@W_1#Application.M.hmi.pf.px[138]",
	"@W_1#Application.M.hmi.pf.px[139]",
	"@W_1#Application.M.hmi.pf.px[140]",
	"@W_1#Application.M.hmi.pf.px[141]",
	"@W_1#Application.M.hmi.pf.px[142]",
	"@W_1#Application.M.hmi.pf.px[143]",
	"@W_1#Application.M.hmi.pf.px[144]",
	"@W_1#Application.M.hmi.pf.px[145]",
	"@W_1#Application.M.hmi.pf.px[146]",
	"@W_1#Application.M.hmi.pf.px[147]",
	"@W_1#Application.M.hmi.pf.px[148]",
	"@W_1#Application.M.hmi.pf.px[149]",
	"@W_1#Application.M.hmi.pf.px[150]",
	"@W_1#Application.M.hmi.pf.px[151]",
	"@W_1#Application.M.hmi.pf.px[152]",
	"@W_1#Application.M.hmi.pf.px[153]",
	"@W_1#Application.M.hmi.pf.px[154]",
	"@W_1#Application.M.hmi.pf.px[155]",
	"@W_1#Application.M.hmi.pf.px[156]",
	"@W_1#Application.M.hmi.pf.px[157]",
	"@W_1#Application.M.hmi.pf.px[158]",
	"@W_1#Application.M.hmi.pf.px[159]",
	"@W_1#Application.M.hmi.pf.px[160]",
	"@W_1#Application.M.hmi.pf.px[161]",
	"@W_1#Application.M.hmi.pf.px[162]",
	"@W_1#Application.M.hmi.pf.px[163]",
	"@W_1#Application.M.hmi.pf.px[164]",
	"@W_1#Application.M.hmi.pf.px[165]",
	"@W_1#Application.M.hmi.pf.px[166]",
	"@W_1#Application.M.hmi.pf.px[167]",
	"@W_1#Application.M.hmi.pf.px[168]",
	"@W_1#Application.M.hmi.pf.px[169]",
	"@W_1#Application.M.hmi.pf.px[170]",
	"@W_1#Application.M.hmi.pf.px[171]",
	"@W_1#Application.M.hmi.pf.px[172]",
	"@W_1#Application.M.hmi.pf.px[173]",
	"@W_1#Application.M.hmi.pf.px[174]",
	"@W_1#Application.M.hmi.pf.px[175]",
	"@W_1#Application.M.hmi.pf.px[176]",
	"@W_1#Application.M.hmi.pf.px[177]",
	"@W_1#Application.M.hmi.pf.px[178]",
	"@W_1#Application.M.hmi.pf.px[179]",
	"@W_1#Application.M.hmi.pf.px[180]",
	"@W_1#Application.M.hmi.pf.px[181]",
	"@W_1#Application.M.hmi.pf.px[182]",
	"@W_1#Application.M.hmi.pf.px[183]",
	"@W_1#Application.M.hmi.pf.px[184]",
	"@W_1#Application.M.hmi.pf.px[185]",
	"@W_1#Application.M.hmi.pf.px[186]",
	"@W_1#Application.M.hmi.pf.px[187]",
	"@W_1#Application.M.hmi.pf.px[188]",
	"@W_1#Application.M.hmi.pf.px[189]",
	"@W_1#Application.M.hmi.pf.px[190]",
	"@W_1#Application.M.hmi.pf.px[191]",
	"@W_1#Application.M.hmi.pf.px[192]",
	"@W_1#Application.M.hmi.pf.px[193]",
	"@W_1#Application.M.hmi.pf.px[194]",
	"@W_1#Application.M.hmi.pf.px[195]",
	"@W_1#Application.M.hmi.pf.px[196]",
	"@W_1#Application.M.hmi.pf.px[197]",
	"@W_1#Application.M.hmi.pf.px[198]",
	"@W_1#Application.M.hmi.pf.px[199]",
	"@W_1#Application.M.hmi.pf.px[200]",
	"@W_1#Application.M.hmi.pf.px[201]",
	"@W_1#Application.M.hmi.pf.px[202]",
	"@W_1#Application.M.hmi.pf.px[203]",
	"@W_1#Application.M.hmi.pf.px[204]",
	"@W_1#Application.M.hmi.pf.px[205]",
	"@W_1#Application.M.hmi.pf.px[206]",
	"@W_1#Application.M.hmi.pf.px[207]",
	"@W_1#Application.M.hmi.pf.px[208]",
	"@W_1#Application.M.hmi.pf.px[209]",
	"@W_1#Application.M.hmi.pf.px[210]",
	"@W_1#Application.M.hmi.pf.px[211]",
	"@W_1#Application.M.hmi.pf.px[212]",
	"@W_1#Application.M.hmi.pf.px[213]",
	"@W_1#Application.M.hmi.pf.px[214]",
	"@W_1#Application.M.hmi.pf.px[215]",
	"@W_1#Application.M.hmi.pf.px[216]",
	"@W_1#Application.M.hmi.pf.px[217]",
	"@W_1#Application.M.hmi.pf.px[218]",
	"@W_1#Application.M.hmi.pf.px[219]",
	"@W_1#Application.M.hmi.pf.px[220]",
	"@W_1#Application.M.hmi.pf.px[221]",
	"@W_1#Application.M.hmi.pf.px[222]",
	"@W_1#Application.M.hmi.pf.px[223]",
	"@W_1#Application.M.hmi.pf.px[224]",
	"@W_1#Application.M.hmi.pf.px[225]",
	"@W_1#Application.M.hmi.pf.px[226]",
	"@W_1#Application.M.hmi.pf.px[227]",
	"@W_1#Application.M.hmi.pf.px[228]",
	"@W_1#Application.M.hmi.pf.px[229]",
	"@W_1#Application.M.hmi.pf.px[230]",
	"@W_1#Application.M.hmi.pf.px[231]",
	"@W_1#Application.M.hmi.pf.px[232]",
	"@W_1#Application.M.hmi.pf.px[233]",
	"@W_1#Application.M.hmi.pf.px[234]",
	"@W_1#Application.M.hmi.pf.px[235]",
	"@W_1#Application.M.hmi.pf.px[236]",
	"@W_1#Application.M.hmi.pf.px[237]",
	"@W_1#Application.M.hmi.pf.px[238]",
	"@W_1#Application.M.hmi.pf.px[239]",
	"@W_1#Application.M.hmi.pf.px[240]",
	"@W_1#Application.M.hmi.pf.px[241]",
	"@W_1#Application.M.hmi.pf.px[242]",
	"@W_1#Application.M.hmi.pf.px[243]",
	"@W_1#Application.M.hmi.pf.px[244]",
	"@W_1#Application.M.hmi.pf.px[245]",
	"@W_1#Application.M.hmi.pf.px[246]",
	"@W_1#Application.M.hmi.pf.px[247]",
	"@W_1#Application.M.hmi.pf.px[248]",
	"@W_1#Application.M.hmi.pf.px[249]",
	"@W_1#Application.M.hmi.pf.px[250]",
	"@W_1#Application.M.hmi.pf.px[251]",
	"@W_1#Application.M.hmi.pf.px[252]",
	"@W_1#Application.M.hmi.pf.px[253]",
	"@W_1#Application.M.hmi.pf.px[254]",
	"@W_1#Application.M.hmi.pf.px[255]",
	"@W_1#Application.M.hmi.pf.px[256]",
	"@W_1#Application.M.hmi.pf.px[257]",
	"@W_1#Application.M.hmi.pf.px[258]",
	"@W_1#Application.M.hmi.pf.px[259]",
	"@W_1#Application.M.hmi.pf.px[260]",
	"@W_1#Application.M.hmi.pf.px[261]",
	"@W_1#Application.M.hmi.pf.px[262]",
	"@W_1#Application.M.hmi.pf.px[263]",
	"@W_1#Application.M.hmi.pf.px[264]",
	"@W_1#Application.M.hmi.pf.px[265]",
	"@W_1#Application.M.hmi.pf.px[266]",
	"@W_1#Application.M.hmi.pf.px[267]",
	"@W_1#Application.M.hmi.pf.px[268]",
	"@W_1#Application.M.hmi.pf.px[269]",
	"@W_1#Application.M.hmi.pf.px[270]",
	"@W_1#Application.M.hmi.pf.px[271]",
	"@W_1#Application.M.hmi.pf.px[272]",
	"@W_1#Application.M.hmi.pf.px[273]",
	"@W_1#Application.M.hmi.pf.px[274]",
	"@W_1#Application.M.hmi.pf.px[275]",
	"@W_1#Application.M.hmi.pf.px[276]",
	"@W_1#Application.M.hmi.pf.px[277]",
	"@W_1#Application.M.hmi.pf.px[278]",
	"@W_1#Application.M.hmi.pf.px[279]",
	"@W_1#Application.M.hmi.pf.px[280]",
	"@W_1#Application.M.hmi.pf.px[281]",
	"@W_1#Application.M.hmi.pf.px[282]",
	"@W_1#Application.M.hmi.pf.px[283]",
	"@W_1#Application.M.hmi.pf.px[284]",
	"@W_1#Application.M.hmi.pf.px[285]",
	"@W_1#Application.M.hmi.pf.px[286]",
	"@W_1#Application.M.hmi.pf.px[287]",
	"@W_1#Application.M.hmi.pf.px[288]",
	"@W_1#Application.M.hmi.pf.px[289]",
	"@W_1#Application.M.hmi.pf.px[290]",
	"@W_1#Application.M.hmi.pf.px[291]",
	"@W_1#Application.M.hmi.pf.px[292]",
	"@W_1#Application.M.hmi.pf.px[293]",
	"@W_1#Application.M.hmi.pf.px[294]",
	"@W_1#Application.M.hmi.pf.px[295]",
	"@W_1#Application.M.hmi.pf.px[296]",
	"@W_1#Application.M.hmi.pf.px[297]",
	"@W_1#Application.M.hmi.pf.px[298]",
	"@W_1#Application.M.hmi.pf.px[299]",
	"@W_1#Application.M.hmi.pf.px[300]",
	"@W_1#Application.M.hmi.pf.px[301]",
	"@W_1#Application.M.hmi.pf.px[302]",
	"@W_1#Application.M.hmi.pf.px[303]",
	"@W_1#Application.M.hmi.pf.px[304]",
	"@W_1#Application.M.hmi.pf.px[305]",
	"@W_1#Application.M.hmi.pf.px[306]",
	"@W_1#Application.M.hmi.pf.px[307]",
	"@W_1#Application.M.hmi.pf.px[308]",
	"@W_1#Application.M.hmi.pf.px[309]",
	"@W_1#Application.M.hmi.pf.px[310]",
	"@W_1#Application.M.hmi.pf.px[311]",
	"@W_1#Application.M.hmi.pf.px[312]",
	"@W_1#Application.M.hmi.pf.px[313]",
	"@W_1#Application.M.hmi.pf.px[314]",
	"@W_1#Application.M.hmi.pf.px[315]",
	"@W_1#Application.M.hmi.pf.px[316]",
	"@W_1#Application.M.hmi.pf.px[317]",
	"@W_1#Application.M.hmi.pf.px[318]",
	"@W_1#Application.M.hmi.pf.px[319]",
	"@W_1#Application.M.hmi.pf.px[320]",
	"@W_1#Application.M.hmi.pf.px[321]",
	"@W_1#Application.M.hmi.pf.px[322]",
	"@W_1#Application.M.hmi.pf.px[323]",
	"@W_1#Application.M.hmi.pf.px[324]",
	"@W_1#Application.M.hmi.pf.px[325]",
	"@W_1#Application.M.hmi.pf.px[326]",
	"@W_1#Application.M.hmi.pf.px[327]",
	"@W_1#Application.M.hmi.pf.px[328]",
	"@W_1#Application.M.hmi.pf.px[329]",
	"@W_1#Application.M.hmi.pf.px[330]",
	"@W_1#Application.M.hmi.pf.px[331]",
	"@W_1#Application.M.hmi.pf.px[332]",
	"@W_1#Application.M.hmi.pf.px[333]",
	"@W_1#Application.M.hmi.pf.px[334]",
	"@W_1#Application.M.hmi.pf.px[335]",
	"@W_1#Application.M.hmi.pf.px[336]",
	"@W_1#Application.M.hmi.pf.px[337]",
	"@W_1#Application.M.hmi.pf.px[338]",
	"@W_1#Application.M.hmi.pf.px[339]",
	"@W_1#Application.M.hmi.pf.px[340]",
	"@W_1#Application.M.hmi.pf.px[341]",
	"@W_1#Application.M.hmi.pf.px[342]",
	"@W_1#Application.M.hmi.pf.px[343]",
	"@W_1#Application.M.hmi.pf.px[344]",
	"@W_1#Application.M.hmi.pf.px[345]",
	"@W_1#Application.M.hmi.pf.px[346]",
	"@W_1#Application.M.hmi.pf.px[347]",
	"@W_1#Application.M.hmi.pf.px[348]",
	"@W_1#Application.M.hmi.pf.px[349]",
	"@W_1#Application.M.hmi.pf.px[350]",
	"@W_1#Application.M.hmi.pf.px[351]",
	"@W_1#Application.M.hmi.pf.px[352]",
	"@W_1#Application.M.hmi.pf.px[353]",
	"@W_1#Application.M.hmi.pf.px[354]",
	"@W_1#Application.M.hmi.pf.px[355]",
	"@W_1#Application.M.hmi.pf.px[356]",
	"@W_1#Application.M.hmi.pf.px[357]",
	"@W_1#Application.M.hmi.pf.px[358]",
	"@W_1#Application.M.hmi.pf.px[359]",
	"@W_1#Application.M.hmi.pf.px[360]",
	"@W_1#Application.M.hmi.pf.px[361]",
	"@W_1#Application.M.hmi.pf.px[362]",
	"@W_1#Application.M.hmi.pf.px[363]",
	"@W_1#Application.M.hmi.pf.px[364]",
	"@W_1#Application.M.hmi.pf.px[365]",
	"@W_1#Application.M.hmi.pf.px[366]",
	"@W_1#Application.M.hmi.pf.px[367]",
	"@W_1#Application.M.hmi.pf.px[368]",
	"@W_1#Application.M.hmi.pf.px[369]",
	"@W_1#Application.M.hmi.pf.px[370]",
	"@W_1#Application.M.hmi.pf.px[371]",
	"@W_1#Application.M.hmi.pf.px[372]",
	"@W_1#Application.M.hmi.pf.px[373]",
	"@W_1#Application.M.hmi.pf.px[374]",
	"@W_1#Application.M.hmi.pf.px[375]",
	"@W_1#Application.M.hmi.pf.px[376]",
	"@W_1#Application.M.hmi.pf.px[377]",
	"@W_1#Application.M.hmi.pf.px[378]",
	"@W_1#Application.M.hmi.pf.px[379]",
	"@W_1#Application.M.hmi.pf.px[380]",
	"@W_1#Application.M.hmi.pf.px[381]",
	"@W_1#Application.M.hmi.pf.px[382]",
	"@W_1#Application.M.hmi.pf.px[383]",
	"@W_1#Application.M.hmi.pf.px[384]",
	"@W_1#Application.M.hmi.pf.px[385]",
	"@W_1#Application.M.hmi.pf.px[386]",
	"@W_1#Application.M.hmi.pf.px[387]",
	"@W_1#Application.M.hmi.pf.px[388]",
	"@W_1#Application.M.hmi.pf.px[389]",
	"@W_1#Application.M.hmi.pf.px[390]",
	"@W_1#Application.M.hmi.pf.px[391]",
	"@W_1#Application.M.hmi.pf.px[392]",
	"@W_1#Application.M.hmi.pf.px[393]",
	"@W_1#Application.M.hmi.pf.px[394]",
	"@W_1#Application.M.hmi.pf.px[395]",
	"@W_1#Application.M.hmi.pf.px[396]",
	"@W_1#Application.M.hmi.pf.px[397]",
	"@W_1#Application.M.hmi.pf.px[398]",
	"@W_1#Application.M.hmi.pf.px[399]",
	"@W_1#Application.M.hmi.pf.px[400]",
	"@W_1#Application.M.hmi.pf.px[401]",
	"@W_1#Application.M.hmi.pf.px[402]",
	"@W_1#Application.M.hmi.pf.px[403]",
	"@W_1#Application.M.hmi.pf.px[404]",
	"@W_1#Application.M.hmi.pf.px[405]",
	"@W_1#Application.M.hmi.pf.px[406]",
	"@W_1#Application.M.hmi.pf.px[407]",
	"@W_1#Application.M.hmi.pf.px[408]",
	"@W_1#Application.M.hmi.pf.px[409]",
	"@W_1#Application.M.hmi.pf.px[410]",
	"@W_1#Application.M.hmi.pf.px[411]",
	"@W_1#Application.M.hmi.pf.px[412]",
	"@W_1#Application.M.hmi.pf.px[413]",
	"@W_1#Application.M.hmi.pf.px[414]",
	"@W_1#Application.M.hmi.pf.px[415]",
	"@W_1#Application.M.hmi.pf.px[416]",
	"@W_1#Application.M.hmi.pf.px[417]",
	"@W_1#Application.M.hmi.pf.px[418]",
	"@W_1#Application.M.hmi.pf.px[419]",
	"@W_1#Application.M.hmi.pf.px[420]",
	"@W_1#Application.M.hmi.pf.px[421]",
	"@W_1#Application.M.hmi.pf.px[422]",
	"@W_1#Application.M.hmi.pf.px[423]",
	"@W_1#Application.M.hmi.pf.px[424]",
	"@W_1#Application.M.hmi.pf.px[425]",
	"@W_1#Application.M.hmi.pf.px[426]",
	"@W_1#Application.M.hmi.pf.px[427]",
	"@W_1#Application.M.hmi.pf.px[428]",
	"@W_1#Application.M.hmi.pf.px[429]",
	"@W_1#Application.M.hmi.pf.px[430]",
	"@W_1#Application.M.hmi.pf.px[431]",
	"@W_1#Application.M.hmi.pf.px[432]",
	"@W_1#Application.M.hmi.pf.px[433]",
	"@W_1#Application.M.hmi.pf.px[434]",
	"@W_1#Application.M.hmi.pf.px[435]",
	"@W_1#Application.M.hmi.pf.px[436]",
	"@W_1#Application.M.hmi.pf.px[437]",
	"@W_1#Application.M.hmi.pf.px[438]",
	"@W_1#Application.M.hmi.pf.px[439]",
	"@W_1#Application.M.hmi.pf.px[440]",
	"@W_1#Application.M.hmi.pf.px[441]",
	"@W_1#Application.M.hmi.pf.px[442]",
	"@W_1#Application.M.hmi.pf.px[443]",
	"@W_1#Application.M.hmi.pf.px[444]",
	"@W_1#Application.M.hmi.pf.px[445]",
	"@W_1#Application.M.hmi.pf.px[446]",
	"@W_1#Application.M.hmi.pf.px[447]",
	"@W_1#Application.M.hmi.pf.px[448]",
	"@W_1#Application.M.hmi.pf.px[449]",
	"@W_1#Application.M.hmi.pf.px[450]",
	"@W_1#Application.M.hmi.pf.px[451]",
	"@W_1#Application.M.hmi.pf.px[452]",
	"@W_1#Application.M.hmi.pf.px[453]",
	"@W_1#Application.M.hmi.pf.px[454]",
	"@W_1#Application.M.hmi.pf.px[455]",
	"@W_1#Application.M.hmi.pf.px[456]",
	"@W_1#Application.M.hmi.pf.px[457]",
	"@W_1#Application.M.hmi.pf.px[458]",
	"@W_1#Application.M.hmi.pf.px[459]",
	"@W_1#Application.M.hmi.pf.px[460]",
	"@W_1#Application.M.hmi.pf.px[461]",
	"@W_1#Application.M.hmi.pf.px[462]",
	"@W_1#Application.M.hmi.pf.px[463]",
	"@W_1#Application.M.hmi.pf.px[464]",
	"@W_1#Application.M.hmi.pf.px[465]",
	"@W_1#Application.M.hmi.pf.px[466]",
	"@W_1#Application.M.hmi.pf.px[467]",
	"@W_1#Application.M.hmi.pf.px[468]",
	"@W_1#Application.M.hmi.pf.px[469]",
	"@W_1#Application.M.hmi.pf.px[470]",
	"@W_1#Application.M.hmi.pf.px[471]",
	"@W_1#Application.M.hmi.pf.px[472]",
	"@W_1#Application.M.hmi.pf.px[473]",
	"@W_1#Application.M.hmi.pf.px[474]",
	"@W_1#Application.M.hmi.pf.px[475]",
	"@W_1#Application.M.hmi.pf.px[476]",
	"@W_1#Application.M.hmi.pf.px[477]",
	"@W_1#Application.M.hmi.pf.px[478]",
	"@W_1#Application.M.hmi.pf.px[479]",
	"@W_1#Application.M.hmi.pf.px[480]",
	"@W_1#Application.M.hmi.pf.px[481]",
	"@W_1#Application.M.hmi.pf.px[482]",
	"@W_1#Application.M.hmi.pf.px[483]",
	"@W_1#Application.M.hmi.pf.px[484]",
	"@W_1#Application.M.hmi.pf.px[485]",
	"@W_1#Application.M.hmi.pf.px[486]",
	"@W_1#Application.M.hmi.pf.px[487]",
	"@W_1#Application.M.hmi.pf.px[488]",
	"@W_1#Application.M.hmi.pf.px[489]",
	"@W_1#Application.M.hmi.pf.px[490]",
	"@W_1#Application.M.hmi.pf.px[491]",
	"@W_1#Application.M.hmi.pf.px[492]",
	"@W_1#Application.M.hmi.pf.px[493]",
	"@W_1#Application.M.hmi.pf.px[494]",
	"@W_1#Application.M.hmi.pf.px[495]",
	"@W_1#Application.M.hmi.pf.px[496]",
	"@W_1#Application.M.hmi.pf.px[497]",
	"@W_1#Application.M.hmi.pf.px[498]",
	"@W_1#Application.M.hmi.pf.px[499]",
	"@W_1#Application.M.hmi.pf.px[500]",
	"@W_1#Application.M.hmi.pf.px[501]",
	"@W_1#Application.M.hmi.pf.px[502]",
	"@W_1#Application.M.hmi.pf.px[503]",
	"@W_1#Application.M.hmi.pf.px[504]",
	"@W_1#Application.M.hmi.pf.px[505]",
	"@W_1#Application.M.hmi.pf.px[506]",
	"@W_1#Application.M.hmi.pf.px[507]",
	"@W_1#Application.M.hmi.pf.px[508]",
	"@W_1#Application.M.hmi.pf.px[509]",
	"@W_1#Application.M.hmi.pf.px[510]",
	"@W_1#Application.M.hmi.pf.px[511]"
}

local draw_id_py = {
	"@W_1#Application.M.hmi.pf.py[0]",
	"@W_1#Application.M.hmi.pf.py[1]",
	"@W_1#Application.M.hmi.pf.py[2]",
	"@W_1#Application.M.hmi.pf.py[3]",
	"@W_1#Application.M.hmi.pf.py[4]",
	"@W_1#Application.M.hmi.pf.py[5]",
	"@W_1#Application.M.hmi.pf.py[6]",
	"@W_1#Application.M.hmi.pf.py[7]",
	"@W_1#Application.M.hmi.pf.py[8]",
	"@W_1#Application.M.hmi.pf.py[9]",
	"@W_1#Application.M.hmi.pf.py[10]",
	"@W_1#Application.M.hmi.pf.py[11]",
	"@W_1#Application.M.hmi.pf.py[12]",
	"@W_1#Application.M.hmi.pf.py[13]",
	"@W_1#Application.M.hmi.pf.py[14]",
	"@W_1#Application.M.hmi.pf.py[15]",
	"@W_1#Application.M.hmi.pf.py[16]",
	"@W_1#Application.M.hmi.pf.py[17]",
	"@W_1#Application.M.hmi.pf.py[18]",
	"@W_1#Application.M.hmi.pf.py[19]",
	"@W_1#Application.M.hmi.pf.py[20]",
	"@W_1#Application.M.hmi.pf.py[21]",
	"@W_1#Application.M.hmi.pf.py[22]",
	"@W_1#Application.M.hmi.pf.py[23]",
	"@W_1#Application.M.hmi.pf.py[24]",
	"@W_1#Application.M.hmi.pf.py[25]",
	"@W_1#Application.M.hmi.pf.py[26]",
	"@W_1#Application.M.hmi.pf.py[27]",
	"@W_1#Application.M.hmi.pf.py[28]",
	"@W_1#Application.M.hmi.pf.py[29]",
	"@W_1#Application.M.hmi.pf.py[30]",
	"@W_1#Application.M.hmi.pf.py[31]",
	"@W_1#Application.M.hmi.pf.py[32]",
	"@W_1#Application.M.hmi.pf.py[33]",
	"@W_1#Application.M.hmi.pf.py[34]",
	"@W_1#Application.M.hmi.pf.py[35]",
	"@W_1#Application.M.hmi.pf.py[36]",
	"@W_1#Application.M.hmi.pf.py[37]",
	"@W_1#Application.M.hmi.pf.py[38]",
	"@W_1#Application.M.hmi.pf.py[39]",
	"@W_1#Application.M.hmi.pf.py[40]",
	"@W_1#Application.M.hmi.pf.py[41]",
	"@W_1#Application.M.hmi.pf.py[42]",
	"@W_1#Application.M.hmi.pf.py[43]",
	"@W_1#Application.M.hmi.pf.py[44]",
	"@W_1#Application.M.hmi.pf.py[45]",
	"@W_1#Application.M.hmi.pf.py[46]",
	"@W_1#Application.M.hmi.pf.py[47]",
	"@W_1#Application.M.hmi.pf.py[48]",
	"@W_1#Application.M.hmi.pf.py[49]",
	"@W_1#Application.M.hmi.pf.py[50]",
	"@W_1#Application.M.hmi.pf.py[51]",
	"@W_1#Application.M.hmi.pf.py[52]",
	"@W_1#Application.M.hmi.pf.py[53]",
	"@W_1#Application.M.hmi.pf.py[54]",
	"@W_1#Application.M.hmi.pf.py[55]",
	"@W_1#Application.M.hmi.pf.py[56]",
	"@W_1#Application.M.hmi.pf.py[57]",
	"@W_1#Application.M.hmi.pf.py[58]",
	"@W_1#Application.M.hmi.pf.py[59]",
	"@W_1#Application.M.hmi.pf.py[60]",
	"@W_1#Application.M.hmi.pf.py[61]",
	"@W_1#Application.M.hmi.pf.py[62]",
	"@W_1#Application.M.hmi.pf.py[63]",
	"@W_1#Application.M.hmi.pf.py[64]",
	"@W_1#Application.M.hmi.pf.py[65]",
	"@W_1#Application.M.hmi.pf.py[66]",
	"@W_1#Application.M.hmi.pf.py[67]",
	"@W_1#Application.M.hmi.pf.py[68]",
	"@W_1#Application.M.hmi.pf.py[69]",
	"@W_1#Application.M.hmi.pf.py[70]",
	"@W_1#Application.M.hmi.pf.py[71]",
	"@W_1#Application.M.hmi.pf.py[72]",
	"@W_1#Application.M.hmi.pf.py[73]",
	"@W_1#Application.M.hmi.pf.py[74]",
	"@W_1#Application.M.hmi.pf.py[75]",
	"@W_1#Application.M.hmi.pf.py[76]",
	"@W_1#Application.M.hmi.pf.py[77]",
	"@W_1#Application.M.hmi.pf.py[78]",
	"@W_1#Application.M.hmi.pf.py[79]",
	"@W_1#Application.M.hmi.pf.py[80]",
	"@W_1#Application.M.hmi.pf.py[81]",
	"@W_1#Application.M.hmi.pf.py[82]",
	"@W_1#Application.M.hmi.pf.py[83]",
	"@W_1#Application.M.hmi.pf.py[84]",
	"@W_1#Application.M.hmi.pf.py[85]",
	"@W_1#Application.M.hmi.pf.py[86]",
	"@W_1#Application.M.hmi.pf.py[87]",
	"@W_1#Application.M.hmi.pf.py[88]",
	"@W_1#Application.M.hmi.pf.py[89]",
	"@W_1#Application.M.hmi.pf.py[90]",
	"@W_1#Application.M.hmi.pf.py[91]",
	"@W_1#Application.M.hmi.pf.py[92]",
	"@W_1#Application.M.hmi.pf.py[93]",
	"@W_1#Application.M.hmi.pf.py[94]",
	"@W_1#Application.M.hmi.pf.py[95]",
	"@W_1#Application.M.hmi.pf.py[96]",
	"@W_1#Application.M.hmi.pf.py[97]",
	"@W_1#Application.M.hmi.pf.py[98]",
	"@W_1#Application.M.hmi.pf.py[99]",
	"@W_1#Application.M.hmi.pf.py[100]",
	"@W_1#Application.M.hmi.pf.py[101]",
	"@W_1#Application.M.hmi.pf.py[102]",
	"@W_1#Application.M.hmi.pf.py[103]",
	"@W_1#Application.M.hmi.pf.py[104]",
	"@W_1#Application.M.hmi.pf.py[105]",
	"@W_1#Application.M.hmi.pf.py[106]",
	"@W_1#Application.M.hmi.pf.py[107]",
	"@W_1#Application.M.hmi.pf.py[108]",
	"@W_1#Application.M.hmi.pf.py[109]",
	"@W_1#Application.M.hmi.pf.py[110]",
	"@W_1#Application.M.hmi.pf.py[111]",
	"@W_1#Application.M.hmi.pf.py[112]",
	"@W_1#Application.M.hmi.pf.py[113]",
	"@W_1#Application.M.hmi.pf.py[114]",
	"@W_1#Application.M.hmi.pf.py[115]",
	"@W_1#Application.M.hmi.pf.py[116]",
	"@W_1#Application.M.hmi.pf.py[117]",
	"@W_1#Application.M.hmi.pf.py[118]",
	"@W_1#Application.M.hmi.pf.py[119]",
	"@W_1#Application.M.hmi.pf.py[120]",
	"@W_1#Application.M.hmi.pf.py[121]",
	"@W_1#Application.M.hmi.pf.py[122]",
	"@W_1#Application.M.hmi.pf.py[123]",
	"@W_1#Application.M.hmi.pf.py[124]",
	"@W_1#Application.M.hmi.pf.py[125]",
	"@W_1#Application.M.hmi.pf.py[126]",
	"@W_1#Application.M.hmi.pf.py[127]",
	"@W_1#Application.M.hmi.pf.py[128]",
	"@W_1#Application.M.hmi.pf.py[129]",
	"@W_1#Application.M.hmi.pf.py[130]",
	"@W_1#Application.M.hmi.pf.py[131]",
	"@W_1#Application.M.hmi.pf.py[132]",
	"@W_1#Application.M.hmi.pf.py[133]",
	"@W_1#Application.M.hmi.pf.py[134]",
	"@W_1#Application.M.hmi.pf.py[135]",
	"@W_1#Application.M.hmi.pf.py[136]",
	"@W_1#Application.M.hmi.pf.py[137]",
	"@W_1#Application.M.hmi.pf.py[138]",
	"@W_1#Application.M.hmi.pf.py[139]",
	"@W_1#Application.M.hmi.pf.py[140]",
	"@W_1#Application.M.hmi.pf.py[141]",
	"@W_1#Application.M.hmi.pf.py[142]",
	"@W_1#Application.M.hmi.pf.py[143]",
	"@W_1#Application.M.hmi.pf.py[144]",
	"@W_1#Application.M.hmi.pf.py[145]",
	"@W_1#Application.M.hmi.pf.py[146]",
	"@W_1#Application.M.hmi.pf.py[147]",
	"@W_1#Application.M.hmi.pf.py[148]",
	"@W_1#Application.M.hmi.pf.py[149]",
	"@W_1#Application.M.hmi.pf.py[150]",
	"@W_1#Application.M.hmi.pf.py[151]",
	"@W_1#Application.M.hmi.pf.py[152]",
	"@W_1#Application.M.hmi.pf.py[153]",
	"@W_1#Application.M.hmi.pf.py[154]",
	"@W_1#Application.M.hmi.pf.py[155]",
	"@W_1#Application.M.hmi.pf.py[156]",
	"@W_1#Application.M.hmi.pf.py[157]",
	"@W_1#Application.M.hmi.pf.py[158]",
	"@W_1#Application.M.hmi.pf.py[159]",
	"@W_1#Application.M.hmi.pf.py[160]",
	"@W_1#Application.M.hmi.pf.py[161]",
	"@W_1#Application.M.hmi.pf.py[162]",
	"@W_1#Application.M.hmi.pf.py[163]",
	"@W_1#Application.M.hmi.pf.py[164]",
	"@W_1#Application.M.hmi.pf.py[165]",
	"@W_1#Application.M.hmi.pf.py[166]",
	"@W_1#Application.M.hmi.pf.py[167]",
	"@W_1#Application.M.hmi.pf.py[168]",
	"@W_1#Application.M.hmi.pf.py[169]",
	"@W_1#Application.M.hmi.pf.py[170]",
	"@W_1#Application.M.hmi.pf.py[171]",
	"@W_1#Application.M.hmi.pf.py[172]",
	"@W_1#Application.M.hmi.pf.py[173]",
	"@W_1#Application.M.hmi.pf.py[174]",
	"@W_1#Application.M.hmi.pf.py[175]",
	"@W_1#Application.M.hmi.pf.py[176]",
	"@W_1#Application.M.hmi.pf.py[177]",
	"@W_1#Application.M.hmi.pf.py[178]",
	"@W_1#Application.M.hmi.pf.py[179]",
	"@W_1#Application.M.hmi.pf.py[180]",
	"@W_1#Application.M.hmi.pf.py[181]",
	"@W_1#Application.M.hmi.pf.py[182]",
	"@W_1#Application.M.hmi.pf.py[183]",
	"@W_1#Application.M.hmi.pf.py[184]",
	"@W_1#Application.M.hmi.pf.py[185]",
	"@W_1#Application.M.hmi.pf.py[186]",
	"@W_1#Application.M.hmi.pf.py[187]",
	"@W_1#Application.M.hmi.pf.py[188]",
	"@W_1#Application.M.hmi.pf.py[189]",
	"@W_1#Application.M.hmi.pf.py[190]",
	"@W_1#Application.M.hmi.pf.py[191]",
	"@W_1#Application.M.hmi.pf.py[192]",
	"@W_1#Application.M.hmi.pf.py[193]",
	"@W_1#Application.M.hmi.pf.py[194]",
	"@W_1#Application.M.hmi.pf.py[195]",
	"@W_1#Application.M.hmi.pf.py[196]",
	"@W_1#Application.M.hmi.pf.py[197]",
	"@W_1#Application.M.hmi.pf.py[198]",
	"@W_1#Application.M.hmi.pf.py[199]",
	"@W_1#Application.M.hmi.pf.py[200]",
	"@W_1#Application.M.hmi.pf.py[201]",
	"@W_1#Application.M.hmi.pf.py[202]",
	"@W_1#Application.M.hmi.pf.py[203]",
	"@W_1#Application.M.hmi.pf.py[204]",
	"@W_1#Application.M.hmi.pf.py[205]",
	"@W_1#Application.M.hmi.pf.py[206]",
	"@W_1#Application.M.hmi.pf.py[207]",
	"@W_1#Application.M.hmi.pf.py[208]",
	"@W_1#Application.M.hmi.pf.py[209]",
	"@W_1#Application.M.hmi.pf.py[210]",
	"@W_1#Application.M.hmi.pf.py[211]",
	"@W_1#Application.M.hmi.pf.py[212]",
	"@W_1#Application.M.hmi.pf.py[213]",
	"@W_1#Application.M.hmi.pf.py[214]",
	"@W_1#Application.M.hmi.pf.py[215]",
	"@W_1#Application.M.hmi.pf.py[216]",
	"@W_1#Application.M.hmi.pf.py[217]",
	"@W_1#Application.M.hmi.pf.py[218]",
	"@W_1#Application.M.hmi.pf.py[219]",
	"@W_1#Application.M.hmi.pf.py[220]",
	"@W_1#Application.M.hmi.pf.py[221]",
	"@W_1#Application.M.hmi.pf.py[222]",
	"@W_1#Application.M.hmi.pf.py[223]",
	"@W_1#Application.M.hmi.pf.py[224]",
	"@W_1#Application.M.hmi.pf.py[225]",
	"@W_1#Application.M.hmi.pf.py[226]",
	"@W_1#Application.M.hmi.pf.py[227]",
	"@W_1#Application.M.hmi.pf.py[228]",
	"@W_1#Application.M.hmi.pf.py[229]",
	"@W_1#Application.M.hmi.pf.py[230]",
	"@W_1#Application.M.hmi.pf.py[231]",
	"@W_1#Application.M.hmi.pf.py[232]",
	"@W_1#Application.M.hmi.pf.py[233]",
	"@W_1#Application.M.hmi.pf.py[234]",
	"@W_1#Application.M.hmi.pf.py[235]",
	"@W_1#Application.M.hmi.pf.py[236]",
	"@W_1#Application.M.hmi.pf.py[237]",
	"@W_1#Application.M.hmi.pf.py[238]",
	"@W_1#Application.M.hmi.pf.py[239]",
	"@W_1#Application.M.hmi.pf.py[240]",
	"@W_1#Application.M.hmi.pf.py[241]",
	"@W_1#Application.M.hmi.pf.py[242]",
	"@W_1#Application.M.hmi.pf.py[243]",
	"@W_1#Application.M.hmi.pf.py[244]",
	"@W_1#Application.M.hmi.pf.py[245]",
	"@W_1#Application.M.hmi.pf.py[246]",
	"@W_1#Application.M.hmi.pf.py[247]",
	"@W_1#Application.M.hmi.pf.py[248]",
	"@W_1#Application.M.hmi.pf.py[249]",
	"@W_1#Application.M.hmi.pf.py[250]",
	"@W_1#Application.M.hmi.pf.py[251]",
	"@W_1#Application.M.hmi.pf.py[252]",
	"@W_1#Application.M.hmi.pf.py[253]",
	"@W_1#Application.M.hmi.pf.py[254]",
	"@W_1#Application.M.hmi.pf.py[255]",
	"@W_1#Application.M.hmi.pf.py[256]",
	"@W_1#Application.M.hmi.pf.py[257]",
	"@W_1#Application.M.hmi.pf.py[258]",
	"@W_1#Application.M.hmi.pf.py[259]",
	"@W_1#Application.M.hmi.pf.py[260]",
	"@W_1#Application.M.hmi.pf.py[261]",
	"@W_1#Application.M.hmi.pf.py[262]",
	"@W_1#Application.M.hmi.pf.py[263]",
	"@W_1#Application.M.hmi.pf.py[264]",
	"@W_1#Application.M.hmi.pf.py[265]",
	"@W_1#Application.M.hmi.pf.py[266]",
	"@W_1#Application.M.hmi.pf.py[267]",
	"@W_1#Application.M.hmi.pf.py[268]",
	"@W_1#Application.M.hmi.pf.py[269]",
	"@W_1#Application.M.hmi.pf.py[270]",
	"@W_1#Application.M.hmi.pf.py[271]",
	"@W_1#Application.M.hmi.pf.py[272]",
	"@W_1#Application.M.hmi.pf.py[273]",
	"@W_1#Application.M.hmi.pf.py[274]",
	"@W_1#Application.M.hmi.pf.py[275]",
	"@W_1#Application.M.hmi.pf.py[276]",
	"@W_1#Application.M.hmi.pf.py[277]",
	"@W_1#Application.M.hmi.pf.py[278]",
	"@W_1#Application.M.hmi.pf.py[279]",
	"@W_1#Application.M.hmi.pf.py[280]",
	"@W_1#Application.M.hmi.pf.py[281]",
	"@W_1#Application.M.hmi.pf.py[282]",
	"@W_1#Application.M.hmi.pf.py[283]",
	"@W_1#Application.M.hmi.pf.py[284]",
	"@W_1#Application.M.hmi.pf.py[285]",
	"@W_1#Application.M.hmi.pf.py[286]",
	"@W_1#Application.M.hmi.pf.py[287]",
	"@W_1#Application.M.hmi.pf.py[288]",
	"@W_1#Application.M.hmi.pf.py[289]",
	"@W_1#Application.M.hmi.pf.py[290]",
	"@W_1#Application.M.hmi.pf.py[291]",
	"@W_1#Application.M.hmi.pf.py[292]",
	"@W_1#Application.M.hmi.pf.py[293]",
	"@W_1#Application.M.hmi.pf.py[294]",
	"@W_1#Application.M.hmi.pf.py[295]",
	"@W_1#Application.M.hmi.pf.py[296]",
	"@W_1#Application.M.hmi.pf.py[297]",
	"@W_1#Application.M.hmi.pf.py[298]",
	"@W_1#Application.M.hmi.pf.py[299]",
	"@W_1#Application.M.hmi.pf.py[300]",
	"@W_1#Application.M.hmi.pf.py[301]",
	"@W_1#Application.M.hmi.pf.py[302]",
	"@W_1#Application.M.hmi.pf.py[303]",
	"@W_1#Application.M.hmi.pf.py[304]",
	"@W_1#Application.M.hmi.pf.py[305]",
	"@W_1#Application.M.hmi.pf.py[306]",
	"@W_1#Application.M.hmi.pf.py[307]",
	"@W_1#Application.M.hmi.pf.py[308]",
	"@W_1#Application.M.hmi.pf.py[309]",
	"@W_1#Application.M.hmi.pf.py[310]",
	"@W_1#Application.M.hmi.pf.py[311]",
	"@W_1#Application.M.hmi.pf.py[312]",
	"@W_1#Application.M.hmi.pf.py[313]",
	"@W_1#Application.M.hmi.pf.py[314]",
	"@W_1#Application.M.hmi.pf.py[315]",
	"@W_1#Application.M.hmi.pf.py[316]",
	"@W_1#Application.M.hmi.pf.py[317]",
	"@W_1#Application.M.hmi.pf.py[318]",
	"@W_1#Application.M.hmi.pf.py[319]",
	"@W_1#Application.M.hmi.pf.py[320]",
	"@W_1#Application.M.hmi.pf.py[321]",
	"@W_1#Application.M.hmi.pf.py[322]",
	"@W_1#Application.M.hmi.pf.py[323]",
	"@W_1#Application.M.hmi.pf.py[324]",
	"@W_1#Application.M.hmi.pf.py[325]",
	"@W_1#Application.M.hmi.pf.py[326]",
	"@W_1#Application.M.hmi.pf.py[327]",
	"@W_1#Application.M.hmi.pf.py[328]",
	"@W_1#Application.M.hmi.pf.py[329]",
	"@W_1#Application.M.hmi.pf.py[330]",
	"@W_1#Application.M.hmi.pf.py[331]",
	"@W_1#Application.M.hmi.pf.py[332]",
	"@W_1#Application.M.hmi.pf.py[333]",
	"@W_1#Application.M.hmi.pf.py[334]",
	"@W_1#Application.M.hmi.pf.py[335]",
	"@W_1#Application.M.hmi.pf.py[336]",
	"@W_1#Application.M.hmi.pf.py[337]",
	"@W_1#Application.M.hmi.pf.py[338]",
	"@W_1#Application.M.hmi.pf.py[339]",
	"@W_1#Application.M.hmi.pf.py[340]",
	"@W_1#Application.M.hmi.pf.py[341]",
	"@W_1#Application.M.hmi.pf.py[342]",
	"@W_1#Application.M.hmi.pf.py[343]",
	"@W_1#Application.M.hmi.pf.py[344]",
	"@W_1#Application.M.hmi.pf.py[345]",
	"@W_1#Application.M.hmi.pf.py[346]",
	"@W_1#Application.M.hmi.pf.py[347]",
	"@W_1#Application.M.hmi.pf.py[348]",
	"@W_1#Application.M.hmi.pf.py[349]",
	"@W_1#Application.M.hmi.pf.py[350]",
	"@W_1#Application.M.hmi.pf.py[351]",
	"@W_1#Application.M.hmi.pf.py[352]",
	"@W_1#Application.M.hmi.pf.py[353]",
	"@W_1#Application.M.hmi.pf.py[354]",
	"@W_1#Application.M.hmi.pf.py[355]",
	"@W_1#Application.M.hmi.pf.py[356]",
	"@W_1#Application.M.hmi.pf.py[357]",
	"@W_1#Application.M.hmi.pf.py[358]",
	"@W_1#Application.M.hmi.pf.py[359]",
	"@W_1#Application.M.hmi.pf.py[360]",
	"@W_1#Application.M.hmi.pf.py[361]",
	"@W_1#Application.M.hmi.pf.py[362]",
	"@W_1#Application.M.hmi.pf.py[363]",
	"@W_1#Application.M.hmi.pf.py[364]",
	"@W_1#Application.M.hmi.pf.py[365]",
	"@W_1#Application.M.hmi.pf.py[366]",
	"@W_1#Application.M.hmi.pf.py[367]",
	"@W_1#Application.M.hmi.pf.py[368]",
	"@W_1#Application.M.hmi.pf.py[369]",
	"@W_1#Application.M.hmi.pf.py[370]",
	"@W_1#Application.M.hmi.pf.py[371]",
	"@W_1#Application.M.hmi.pf.py[372]",
	"@W_1#Application.M.hmi.pf.py[373]",
	"@W_1#Application.M.hmi.pf.py[374]",
	"@W_1#Application.M.hmi.pf.py[375]",
	"@W_1#Application.M.hmi.pf.py[376]",
	"@W_1#Application.M.hmi.pf.py[377]",
	"@W_1#Application.M.hmi.pf.py[378]",
	"@W_1#Application.M.hmi.pf.py[379]",
	"@W_1#Application.M.hmi.pf.py[380]",
	"@W_1#Application.M.hmi.pf.py[381]",
	"@W_1#Application.M.hmi.pf.py[382]",
	"@W_1#Application.M.hmi.pf.py[383]",
	"@W_1#Application.M.hmi.pf.py[384]",
	"@W_1#Application.M.hmi.pf.py[385]",
	"@W_1#Application.M.hmi.pf.py[386]",
	"@W_1#Application.M.hmi.pf.py[387]",
	"@W_1#Application.M.hmi.pf.py[388]",
	"@W_1#Application.M.hmi.pf.py[389]",
	"@W_1#Application.M.hmi.pf.py[390]",
	"@W_1#Application.M.hmi.pf.py[391]",
	"@W_1#Application.M.hmi.pf.py[392]",
	"@W_1#Application.M.hmi.pf.py[393]",
	"@W_1#Application.M.hmi.pf.py[394]",
	"@W_1#Application.M.hmi.pf.py[395]",
	"@W_1#Application.M.hmi.pf.py[396]",
	"@W_1#Application.M.hmi.pf.py[397]",
	"@W_1#Application.M.hmi.pf.py[398]",
	"@W_1#Application.M.hmi.pf.py[399]",
	"@W_1#Application.M.hmi.pf.py[400]",
	"@W_1#Application.M.hmi.pf.py[401]",
	"@W_1#Application.M.hmi.pf.py[402]",
	"@W_1#Application.M.hmi.pf.py[403]",
	"@W_1#Application.M.hmi.pf.py[404]",
	"@W_1#Application.M.hmi.pf.py[405]",
	"@W_1#Application.M.hmi.pf.py[406]",
	"@W_1#Application.M.hmi.pf.py[407]",
	"@W_1#Application.M.hmi.pf.py[408]",
	"@W_1#Application.M.hmi.pf.py[409]",
	"@W_1#Application.M.hmi.pf.py[410]",
	"@W_1#Application.M.hmi.pf.py[411]",
	"@W_1#Application.M.hmi.pf.py[412]",
	"@W_1#Application.M.hmi.pf.py[413]",
	"@W_1#Application.M.hmi.pf.py[414]",
	"@W_1#Application.M.hmi.pf.py[415]",
	"@W_1#Application.M.hmi.pf.py[416]",
	"@W_1#Application.M.hmi.pf.py[417]",
	"@W_1#Application.M.hmi.pf.py[418]",
	"@W_1#Application.M.hmi.pf.py[419]",
	"@W_1#Application.M.hmi.pf.py[420]",
	"@W_1#Application.M.hmi.pf.py[421]",
	"@W_1#Application.M.hmi.pf.py[422]",
	"@W_1#Application.M.hmi.pf.py[423]",
	"@W_1#Application.M.hmi.pf.py[424]",
	"@W_1#Application.M.hmi.pf.py[425]",
	"@W_1#Application.M.hmi.pf.py[426]",
	"@W_1#Application.M.hmi.pf.py[427]",
	"@W_1#Application.M.hmi.pf.py[428]",
	"@W_1#Application.M.hmi.pf.py[429]",
	"@W_1#Application.M.hmi.pf.py[430]",
	"@W_1#Application.M.hmi.pf.py[431]",
	"@W_1#Application.M.hmi.pf.py[432]",
	"@W_1#Application.M.hmi.pf.py[433]",
	"@W_1#Application.M.hmi.pf.py[434]",
	"@W_1#Application.M.hmi.pf.py[435]",
	"@W_1#Application.M.hmi.pf.py[436]",
	"@W_1#Application.M.hmi.pf.py[437]",
	"@W_1#Application.M.hmi.pf.py[438]",
	"@W_1#Application.M.hmi.pf.py[439]",
	"@W_1#Application.M.hmi.pf.py[440]",
	"@W_1#Application.M.hmi.pf.py[441]",
	"@W_1#Application.M.hmi.pf.py[442]",
	"@W_1#Application.M.hmi.pf.py[443]",
	"@W_1#Application.M.hmi.pf.py[444]",
	"@W_1#Application.M.hmi.pf.py[445]",
	"@W_1#Application.M.hmi.pf.py[446]",
	"@W_1#Application.M.hmi.pf.py[447]",
	"@W_1#Application.M.hmi.pf.py[448]",
	"@W_1#Application.M.hmi.pf.py[449]",
	"@W_1#Application.M.hmi.pf.py[450]",
	"@W_1#Application.M.hmi.pf.py[451]",
	"@W_1#Application.M.hmi.pf.py[452]",
	"@W_1#Application.M.hmi.pf.py[453]",
	"@W_1#Application.M.hmi.pf.py[454]",
	"@W_1#Application.M.hmi.pf.py[455]",
	"@W_1#Application.M.hmi.pf.py[456]",
	"@W_1#Application.M.hmi.pf.py[457]",
	"@W_1#Application.M.hmi.pf.py[458]",
	"@W_1#Application.M.hmi.pf.py[459]",
	"@W_1#Application.M.hmi.pf.py[460]",
	"@W_1#Application.M.hmi.pf.py[461]",
	"@W_1#Application.M.hmi.pf.py[462]",
	"@W_1#Application.M.hmi.pf.py[463]",
	"@W_1#Application.M.hmi.pf.py[464]",
	"@W_1#Application.M.hmi.pf.py[465]",
	"@W_1#Application.M.hmi.pf.py[466]",
	"@W_1#Application.M.hmi.pf.py[467]",
	"@W_1#Application.M.hmi.pf.py[468]",
	"@W_1#Application.M.hmi.pf.py[469]",
	"@W_1#Application.M.hmi.pf.py[470]",
	"@W_1#Application.M.hmi.pf.py[471]",
	"@W_1#Application.M.hmi.pf.py[472]",
	"@W_1#Application.M.hmi.pf.py[473]",
	"@W_1#Application.M.hmi.pf.py[474]",
	"@W_1#Application.M.hmi.pf.py[475]",
	"@W_1#Application.M.hmi.pf.py[476]",
	"@W_1#Application.M.hmi.pf.py[477]",
	"@W_1#Application.M.hmi.pf.py[478]",
	"@W_1#Application.M.hmi.pf.py[479]",
	"@W_1#Application.M.hmi.pf.py[480]",
	"@W_1#Application.M.hmi.pf.py[481]",
	"@W_1#Application.M.hmi.pf.py[482]",
	"@W_1#Application.M.hmi.pf.py[483]",
	"@W_1#Application.M.hmi.pf.py[484]",
	"@W_1#Application.M.hmi.pf.py[485]",
	"@W_1#Application.M.hmi.pf.py[486]",
	"@W_1#Application.M.hmi.pf.py[487]",
	"@W_1#Application.M.hmi.pf.py[488]",
	"@W_1#Application.M.hmi.pf.py[489]",
	"@W_1#Application.M.hmi.pf.py[490]",
	"@W_1#Application.M.hmi.pf.py[491]",
	"@W_1#Application.M.hmi.pf.py[492]",
	"@W_1#Application.M.hmi.pf.py[493]",
	"@W_1#Application.M.hmi.pf.py[494]",
	"@W_1#Application.M.hmi.pf.py[495]",
	"@W_1#Application.M.hmi.pf.py[496]",
	"@W_1#Application.M.hmi.pf.py[497]",
	"@W_1#Application.M.hmi.pf.py[498]",
	"@W_1#Application.M.hmi.pf.py[499]",
	"@W_1#Application.M.hmi.pf.py[500]",
	"@W_1#Application.M.hmi.pf.py[501]",
	"@W_1#Application.M.hmi.pf.py[502]",
	"@W_1#Application.M.hmi.pf.py[503]",
	"@W_1#Application.M.hmi.pf.py[504]",
	"@W_1#Application.M.hmi.pf.py[505]",
	"@W_1#Application.M.hmi.pf.py[506]",
	"@W_1#Application.M.hmi.pf.py[507]",
	"@W_1#Application.M.hmi.pf.py[508]",
	"@W_1#Application.M.hmi.pf.py[509]",
	"@W_1#Application.M.hmi.pf.py[510]",
	"@W_1#Application.M.hmi.pf.py[511]",
}

local draw_pf_in_progress = 0
function draw_pf()
    if draw_pf_in_progress == 1 then
        return false
    end
    draw_pf_in_progress = 1
    local part = "1_CST_0"
    local axisStyle = {
        color = 0x000000,
        linetype = 3,
        width = 1,
        visible = 1,
    }
    local pathStyle = {
        color = 0x00868b,
        linetype = 0,
        width = 1,
        visible = 1,
    }
    local pathDirStyle = {
        color = 0xff6600,
        linetype = 1,
        width = 1,
        visible = 1,
    }
    local indexStyle = {
        color = 0x0000ff,
        linetype = 0,
        width = 2,
        visible = 1,
    }
    local cursorStyle = {
        color = 0xff0000,
        linetype = 2,
        width = 1,
        visible = 1,
    }
    local size = {x = draw_spec.rect_w, y = draw_spec.rect_h}
    local size_x = we_bas_getint(draw_id.size_x)
    local size_y = we_bas_getint(draw_id.size_y)
    if size_x ~= nil and size_y ~= nil and size_x > 1000 and size_y > 1000 then
        size.x = math.ceil(size_x * 1e-3)
        size.y = math.ceil(size_y * 1e-3)
    else
        draw_pf_in_progress = 0
        return false
    end
    local axis = {0, 0, 0, size.y, size.x, size.y, size.x, 0, 0, 0}
    cus_curve.init(part, 1, 1)
    cus_curve.set_range(part, "x", 0, size.x)
    cus_curve.set_range(part, "y", 0, size.y)
    cus_curve.set_line(part, 1, 5, axisStyle)
    cus_curve.set_line(part, 2, 512, pathStyle)
    cus_curve.set_line(part, 3, 6, pathDirStyle)
    cus_curve.set_line(part, 4, draw_spec.index_edge_count + 1, indexStyle)
    cus_curve.set_line(part, 5, 5, cursorStyle)
    cus_curve.draw_line(part, 1, axis)
    --
    draw_pf_path(part, size)
    draw_pf_path_dir(part, size)
    draw_pf_index(part, size)
    draw_pf_cursor(part, size)
    --
    cus_curve.refresh(part)
    draw_pf_in_progress = 0
    return true
end

function draw_pf_path(part, size)
    local p_count = we_bas_getint(draw_id.p_count)
    if p_count == nil then
        p_count = 0
    end
    local path = {}
    local valid = 0
    for i = 1, p_count do
        local x = we_bas_getint(draw_id_px[i])
        local y = we_bas_getint(draw_id_py[i])
        if x ~= nil and y ~= nil then
            table.insert(path, x * 1e-3)
            table.insert(path, y * 1e-3)
            valid = valid + 1
        end
    end
    local sx = size.x / draw_spec.rect_w
    local sy = size.y / draw_spec.rect_h
    if valid == 0 then
        path = draw_circle(0, 0, sx, sy, 7, math.pi / 4, 4)
    elseif valid == 1 then
        path = draw_circle(path[1], path[2], sx, sy, 7, math.pi / 4, 4)
    end
    cus_curve.draw_line(part, 2, path)
end

function draw_pf_path_dir(part, size)
    local p_count = we_bas_getint(draw_id.p_count)
    if p_count == nil then
        p_count = 0
    end
    local sx = size.x / draw_spec.rect_w
    local sy = size.y / draw_spec.rect_h
    local path_dir = {}
    local valid = false
    if p_count >= 2 then
        local a = {x = 0, y = 0}
        local b = {x = 0, y = 0}
        a.x = we_bas_getint(draw_id_px[p_count])
        a.y = we_bas_getint(draw_id_py[p_count])
        b.x = we_bas_getint(draw_id_px[1])
        b.y = we_bas_getint(draw_id_py[1])
        if a.x ~= nil and a.y ~= nil and b.x ~= nil and b.y ~= nil then
            a.x = a.x * 1e-3
            a.y = a.y * 1e-3
            b.x = b.x * 1e-3
            b.y = b.y * 1e-3
            local dx = b.x - a.x
            local dy = b.y - a.y
            local d = math.sqrt(dx * dx + dy * dy)
            local ux = 0
            local uy = 0
            local nx = 0
            local ny = 0
            if d > 0 then
                ux = dx / d
                uy = dy / d
                nx = uy
                ny = -ux
            end
            path_dir[1] = a.x
            path_dir[2] = a.y
            path_dir[3] = b.x - ux * 9 * sx
            path_dir[4] = b.y - uy * 9 * sy
            path_dir[5] = b.x - (ux * 12 - nx * 5) * sx
            path_dir[6] = b.y - (uy * 12 - ny * 5) * sy
            path_dir[7] = b.x
            path_dir[8] = b.y
            path_dir[9] = b.x - (ux * 12 + nx * 5) * sx
            path_dir[10] = b.y - (uy * 12 + ny * 5) * sy
            path_dir[11] = path_dir[3]
            path_dir[12] = path_dir[4]
            valid = true
        end
    end
    if valid == false then
        path_dir = draw_circle(0, 0, sx, sy, 7, math.pi / 4, 4)
    end
    cus_curve.draw_line(part, 3, path_dir)
end

function draw_pf_index(part, size)
    local p_index = we_bas_getint(draw_id.p_index)
    local p_count = we_bas_getint(draw_id.p_count)
    if p_index == nil or p_count == nil then
        return
    end
    local x = we_bas_getint(draw_id_px[p_index + 1])
    local y = we_bas_getint(draw_id_py[p_index + 1])
    if p_index >= p_count then
        x = we_bas_getint(draw_id.p_x)
        y = we_bas_getint(draw_id.p_y)
    end
    if x == nil or y == nil then
        return
    end
    x = x * 1e-3
    y = y * 1e-3
    local sx = size.x / draw_spec.rect_w
    local sy = size.y / draw_spec.rect_h
    cus_curve.draw_line(part, 4, draw_circle(x, y, sx, sy, 6, 0, draw_spec.index_edge_count))
end

function draw_pf_cursor(part, size)
    local x = we_bas_getint(draw_id.p_x)
    local y = we_bas_getint(draw_id.p_y)
    if x == nil or y == nil then
        return
    end
    x = x * 1e-3
    y = y * 1e-3
    local xo = size.x * 2
    local yo = size.y * 2
    local cursor = {}
    cursor[1] = x
    cursor[2] = y + yo
    cursor[3] = x
    cursor[4] = y - yo
    cursor[5] = x - xo
    cursor[6] = y - yo
    cursor[7] = x - xo
    cursor[8] = y
    cursor[9] = x + xo
    cursor[10] = y
    cus_curve.draw_line(part, 5, cursor)
end

function draw_circle(x, y, sx, sy, r, rad, edge_count)
    vts = {}
    for i = 0, edge_count do
        local irad = rad + (math.pi * 2 * i) / edge_count
        vts[i * 2 + 1] = x + math.cos(irad) * r * sx
        vts[i * 2 + 2] = y + math.sin(irad) * r * sy
    end
    return vts
end